//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MifareWindowsTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MifareWindowsTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aborted.
        /// </summary>
        public static string Aborted {
            get {
                return ResourceManager.GetString("Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACR122U tag reader doesn&apos;t seem to be plugged in!.
        /// </summary>
        public static string ACR122NotPlugged {
            get {
                return ResourceManager.GetString("ACR122NotPlugged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dump file.
        /// </summary>
        public static string ADumpFile {
            get {
                return ResourceManager.GetString("ADumpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exists.
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto scan Tag is running.
        /// </summary>
        public static string AutoScanTagRunning {
            get {
                return ResourceManager.GetString("AutoScanTagRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto scan tag stopped.
        /// </summary>
        public static string AutoScanTagStopped {
            get {
                return ResourceManager.GetString("AutoScanTagStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Beep_ACR122U {
            get {
                object obj = ResourceManager.GetObject("Beep_ACR122U", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change UID.
        /// </summary>
        public static string btnChangeUID {
            get {
                return ResourceManager.GetString("btnChangeUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare dumps.
        /// </summary>
        public static string btnCompareDumps {
            get {
                return ResourceManager.GetString("btnCompareDumps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Key File.
        /// </summary>
        public static string BtnDeleteKeyFileContent {
            get {
                return ResourceManager.GetString("BtnDeleteKeyFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Key File.
        /// </summary>
        public static string BtnEditKeyFileContent {
            get {
                return ResourceManager.GetString("BtnEditKeyFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Key File.
        /// </summary>
        public static string BtnNewKeyFileContent {
            get {
                return ResourceManager.GetString("BtnNewKeyFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Dump A.
        /// </summary>
        public static string btnOpenDumpAContent {
            get {
                return ResourceManager.GetString("btnOpenDumpAContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Dump B.
        /// </summary>
        public static string btnOpenDumpBContent {
            get {
                return ResourceManager.GetString("btnOpenDumpBContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Source Dump.
        /// </summary>
        public static string BtnSelectDumpContent {
            get {
                return ResourceManager.GetString("BtnSelectDumpContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start decode &amp; Read tag.
        /// </summary>
        public static string btnStartMappingAndReadTagContent {
            get {
                return ResourceManager.GetString("btnStartMappingAndReadTagContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Dump.
        /// </summary>
        public static string BtnWriteDumpContent {
            get {
                return ResourceManager.GetString("BtnWriteDumpContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use these Access Conditions for all sectors.
        /// </summary>
        public static string CkACsContent {
            get {
                return ResourceManager.GetString("CkACsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced: Enable writing to manufacturer block.
        /// </summary>
        public static string CkEnableBlock0WritingContent {
            get {
                return ResourceManager.GetString("CkEnableBlock0WritingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Periodic Tag AutoScan.
        /// </summary>
        public static string ckEnablePeriodicTagScanContent {
            get {
                return ResourceManager.GetString("ckEnablePeriodicTagScanContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checks if there is a new tag on the tag reader every 3 seconds.
        /// </summary>
        public static string ckEnablePeriodicTagScanTooltip {
            get {
                return ResourceManager.GetString("ckEnablePeriodicTagScanTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cloning.
        /// </summary>
        public static string Cloning {
            get {
                return ResourceManager.GetString("Cloning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Dumps.
        /// </summary>
        public static string CompareDumps {
            get {
                return ResourceManager.GetString("CompareDumps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt tag.
        /// </summary>
        public static string DecryptTagTitle {
            get {
                return ResourceManager.GetString("DecryptTagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different.
        /// </summary>
        public static string Different {
            get {
                return ResourceManager.GetString("Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done with errors.
        /// </summary>
        public static string DoneWithErrors {
            get {
                return ResourceManager.GetString("DoneWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to re-use this dump ?.
        /// </summary>
        public static string DoYouWantToReUseThisDump {
            get {
                return ResourceManager.GetString("DoYouWantToReUseThisDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACR122U Tag reader driver doesn&apos;t seem to be installed.
        ///Click OK to be redirected on the driver download page.
        ///Install driver last version named &apos;MSI Installer for PC / SC Driver&apos;.
        /// </summary>
        public static string DriverACR122NotInstalled {
            get {
                return ResourceManager.GetString("DriverACR122NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACR122U seems to be installed but, NOT the LibUsbK driver.
        ///Click OK to install it.
        /// </summary>
        public static string DriverLibUsbKNonInstalled {
            get {
                return ResourceManager.GetString("DriverLibUsbKNonInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump existing.
        /// </summary>
        public static string DumpExisting {
            get {
                return ResourceManager.GetString("DumpExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump Files|*.dump;*.mfd;*.dmp;*.img|All Files|*.*.
        /// </summary>
        public static string DumpFileFilter {
            get {
                return ResourceManager.GetString("DumpFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump.
        /// </summary>
        public static string DumpWindowTitle {
            get {
                return ResourceManager.GetString("DumpWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT/ADD KEY FILE.
        /// </summary>
        public static string EditAddKeyFile {
            get {
                return ResourceManager.GetString("EditAddKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT/ANALYSE DUMP FILE.
        /// </summary>
        public static string EditAnalyzeDumpFile {
            get {
                return ResourceManager.GetString("EditAnalyzeDumpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Dump.
        /// </summary>
        public static string EditDump {
            get {
                return ResourceManager.GetString("EditDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Key File.
        /// </summary>
        public static string EditKeyFileWindowTitle {
            get {
                return ResourceManager.GetString("EditKeyFileWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Handling.
        /// </summary>
        public static string ErrorHandling {
            get {
                return ResourceManager.GetString("ErrorHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Format.
        /// </summary>
        public static string FactoryFormat {
            get {
                return ResourceManager.GetString("FactoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finished.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format tag.
        /// </summary>
        public static string FormatTag {
            get {
                return ResourceManager.GetString("FormatTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP/INFO.
        /// </summary>
        public static string HelpAndInfo {
            get {
                return ResourceManager.GetString("HelpAndInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identical.
        /// </summary>
        public static string Identical {
            get {
                return ResourceManager.GetString("Identical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid dump file.
        /// </summary>
        public static string InvalidDumpFile {
            get {
                return ResourceManager.GetString("InvalidDumpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid UID (valid UID : 8 hex digits).
        /// </summary>
        public static string InvalidUID {
            get {
                return ResourceManager.GetString("InvalidUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Files|*.keys.
        /// </summary>
        public static string KeyFilesFilter {
            get {
                return ResourceManager.GetString("KeyFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys.
        /// </summary>
        public static string Keys {
            get {
                return ResourceManager.GetString("Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose some key file(s):.
        /// </summary>
        public static string lblChooseKeyFileContent {
            get {
                return ResourceManager.GetString("lblChooseKeyFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Keys.
        /// </summary>
        public static string MapKeyToSectorWindowTitle {
            get {
                return ResourceManager.GetString("MapKeyToSectorWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon MWT {
            get {
                object obj = ResourceManager.GetObject("MWT", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select one source dump.
        /// </summary>
        public static string NeedSelectDumpKeyFileSource {
            get {
                return ResourceManager.GetString("NeedSelectDumpKeyFileSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select one source dump and one target dump.
        /// </summary>
        public static string NeedSelectDumpKeyFileSourceAndTarget {
            get {
                return ResourceManager.GetString("NeedSelectDumpKeyFileSourceAndTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select one target dump.
        /// </summary>
        public static string NeedSelectDumpKeyFileTarget {
            get {
                return ResourceManager.GetString("NeedSelectDumpKeyFileTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select at least one key file.
        /// </summary>
        public static string NeedToSelectOneKeyFile {
            get {
                return ResourceManager.GetString("NeedToSelectOneKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New UID.
        /// </summary>
        public static string NewUID {
            get {
                return ResourceManager.GetString("NewUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new UID Found.
        /// </summary>
        public static string NewUIDFound {
            get {
                return ResourceManager.GetString("NewUIDFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no tag.
        /// </summary>
        public static string NoTag {
            get {
                return ResourceManager.GetString("NoTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Tag detected on reader.
        /// </summary>
        public static string NoTagDetectedOnReader {
            get {
                return ResourceManager.GetString("NoTagDetectedOnReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old UID.
        /// </summary>
        public static string OldUID {
            get {
                return ResourceManager.GetString("OldUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Dump.
        /// </summary>
        public static string OpenDump {
            get {
                return ResourceManager.GetString("OpenDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart Mifare Windows Tool as Administrator.
        /// </summary>
        public static string PleaseRestartAsAdmin {
            get {
                return ResourceManager.GetString("PleaseRestartAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halt on errors.
        /// </summary>
        public static string rbHaltOnErrorContent {
            get {
                return ResourceManager.GetString("rbHaltOnErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolerate errors.
        /// </summary>
        public static string rbTolerateOnErrorContent {
            get {
                return ResourceManager.GetString("rbTolerateOnErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Key A.
        /// </summary>
        public static string RbUseKeyAContent {
            get {
                return ResourceManager.GetString("RbUseKeyAContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Key B.
        /// </summary>
        public static string RbUseKeyBContent {
            get {
                return ResourceManager.GetString("RbUseKeyBContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READ TAG.
        /// </summary>
        public static string ReadTag {
            get {
                return ResourceManager.GetString("ReadTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Dump as.
        /// </summary>
        public static string SaveDumpAs {
            get {
                return ResourceManager.GetString("SaveDumpAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Key File.
        /// </summary>
        public static string SaveKeyFile {
            get {
                return ResourceManager.GetString("SaveKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scan finished.
        /// </summary>
        public static string ScanFinished {
            get {
                return ResourceManager.GetString("ScanFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        public static string Sector {
            get {
                return ResourceManager.GetString("Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Files.
        /// </summary>
        public static string SelectKeyFilesWindowTitle {
            get {
                return ResourceManager.GetString("SelectKeyFilesWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools / Options.
        /// </summary>
        public static string SelectToolWindowTitle {
            get {
                return ResourceManager.GetString("SelectToolWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set new tag UID.
        /// </summary>
        public static string SetUIDWindowTitle {
            get {
                return ResourceManager.GetString("SetUIDWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show as ASCII.
        /// </summary>
        public static string ShowAsASCII {
            get {
                return ResourceManager.GetString("ShowAsASCII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show as Hex.
        /// </summary>
        public static string ShowAsHex {
            get {
                return ResourceManager.GetString("ShowAsHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source dump:.
        /// </summary>
        public static string SourceDump {
            get {
                return ResourceManager.GetString("SourceDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Cloning.
        /// </summary>
        public static string StartCloning {
            get {
                return ResourceManager.GetString("StartCloning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to started.
        /// </summary>
        public static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Type.
        /// </summary>
        public static string TagType {
            get {
                return ResourceManager.GetString("TagType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to target.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target dump:.
        /// </summary>
        public static string TargetDump {
            get {
                return ResourceManager.GetString("TargetDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file is a MCT (Mifare classic tool) dump and it will be automatically converted to MWT dump.
        /// </summary>
        public static string thisismctdumpfile {
            get {
                return ResourceManager.GetString("thisismctdumpfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOOLS / OPTIONS.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FF078069 is the default value.
        /// </summary>
        public static string ttAcsDefaultValue {
            get {
                return ResourceManager.GetString("ttAcsDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (used for source tag mapping).
        /// </summary>
        public static string UsedForSourceMapping {
            get {
                return ResourceManager.GetString("UsedForSourceMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (used for target tag mapping).
        /// </summary>
        public static string UsedForTargetMapping {
            get {
                return ResourceManager.GetString("UsedForTargetMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Dump (Clone).
        /// </summary>
        public static string WriteDumpClone {
            get {
                return ResourceManager.GetString("WriteDumpClone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Tag.
        /// </summary>
        public static string WriteDumpWindowTitle {
            get {
                return ResourceManager.GetString("WriteDumpWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WRITE TAG.
        /// </summary>
        public static string WriteTag {
            get {
                return ResourceManager.GetString("WriteTag", resourceCulture);
            }
        }
    }
}
